#**ðŸ”Ÿ Pandas Practice Questions**

In [112]:
import pandas as pd
import numpy as np

#**Q1. Load & Inspect**

- Read a CSV into a DataFrame.

- Show first/last 5 rows, .info(), .describe().

- List numeric and categorical columns programmatically.

In [78]:
#reading CSV file in Data Frame
url_data = 'https://raw.githubusercontent.com/Vipulraorane/My-practice-files/main/Bank_churn.csv'
df = pd.read_csv(url_data)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
#Show first 5 rows
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
#Show last 5 rows
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [16]:
#Show  .info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [17]:
#.describe().
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [21]:
#List numeric Columns
print(df.select_dtypes(include='number').columns)

print('\n')

#List Categorical Columns
print(df.select_dtypes(include='object').columns)

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')


Index(['Surname', 'Geography', 'Gender'], dtype='object')

#**Q2. Missing values**

- Compute missing count % per column.

- Impute numeric columns with median and categorical with mode (into a new DataFrame).

In [ ]:
#Compute missing count % per column.
df.isnull().sum()

In [33]:
#Impute numeric columns with median
numeric_cols = df.select_dtypes(include='number').columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

In [32]:

# Impute categorical columns with mode
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

#**Q3. Filtering**

- Filter rows by multiple conditions (e.g., CreditScore > 650 and Geography in ["France","Spain"]).

- Count unique values by a given column.

In [40]:
df.head()
df[(df['CreditScore'] > 650) & (df['Geography'].isin(['France','Spain']))]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [49]:
#Count unique values by a Geography column.
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

#**Q4. Grouping**

- Group by a categorical column.

- Compute count, mean, median, std for a numeric column.

- Sort by the aggregated mean descending.

In [69]:
#Loading Sample DF for undertsanding
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [70]:
#identifying the categorical cols
cat_col = df.select_dtypes(include='object').columns
cat_col

Index(['Surname', 'Geography', 'Gender'], dtype='object')

In [81]:
#grouping the categorical column and doing agg for numerical cols
df_1 = df.groupby([cat_col[1],cat_col[2]]).agg({'CreditScore':['count','mean','median','std'],'Age':['count','mean','median','std']})
df_1

                 CreditScore                                 Age             \
                       count        mean median        std count       mean
Geography Gender
France    Female        2261  649.185759  652.0  97.481021  2261  38.773994
          Male          2753  650.064657  653.0  96.649794  2753  38.296404
Germany   Female        1193  653.093881  651.0  98.364962  1193  40.154233
          Male          1316  649.966565  650.5  98.004557  1316  39.424772
Spain     Female        1089  651.769513  653.0  93.571709  1089  39.199265
          Male          1388  650.992075  650.0  95.015124  1388  38.649135


                 median        std
Geography Gender
France    Female   37.0  10.685519
          Male     37.0  10.285569
Germany   Female   39.0  10.461002
          Male     38.0  10.563570
Spain     Female   38.0  10.469659
          Male     37.0  10.425004

In [82]:
#Sort by the aggregated mean descending.
df_1.sort_values(by=('CreditScore','mean'),ascending=False)

                 CreditScore                                 Age             \
                       count        mean median        std count       mean
Geography Gender
Germany   Female        1193  653.093881  651.0  98.364962  1193  40.154233
Spain     Female        1089  651.769513  653.0  93.571709  1089  39.199265
          Male          1388  650.992075  650.0  95.015124  1388  38.649135
France    Male          2753  650.064657  653.0  96.649794  2753  38.296404
Germany   Male          1316  649.966565  650.5  98.004557  1316  39.424772
France    Female        2261  649.185759  652.0  97.481021  2261  38.773994


                 median        std
Geography Gender
Germany   Female   39.0  10.461002
Spain     Female   38.0  10.469659
          Male     37.0  10.425004
France    Male     37.0  10.285569
Germany   Male     38.0  10.563570
France    Female   37.0  10.685519

#**Q5. Multi-aggregation & named agg**

- For sales data with category, price, quantity:

- Compute total revenue, average price, total items per category using agg with named o

In [128]:
#get coffee sales data from kaggle
url_sales = 'https://raw.githubusercontent.com/Vipulraorane/My-practice-files/main/coffee.csv'
df_sales = pd.read_csv(url_sales)
df_sales.head()

         date datetime cash_type                 card  money    coffee_name
0  01-03-2024  15:50.5      card  ANON-0000-0000-0001   38.7          Latte
1  01-03-2024  19:22.5      card  ANON-0000-0000-0002   38.7  Hot Chocolate
2  01-03-2024  20:18.1      card  ANON-0000-0000-0002   38.7  Hot Chocolate
3  01-03-2024  46:33.0      card  ANON-0000-0000-0003   28.9      Americano
4  01-03-2024  48:14.6      card  ANON-0000-0000-0004   38.7          Latte

In [129]:
#Lets Manipulate the Data first
#Drop money column from Data fram
df_sales = df_sales.drop('money',axis=1)

In [130]:
#Lets add new column Quantity and generate a random quantity between 1 - 3
df_sales['Quantity'] = np.random.randint(1, 4, size=len(df_sales))

In [141]:
# set the seed
np.random.seed(42)   # any integer works, e.g. 0, 1, 1234

coffee_prices = {coffee: np.random.randint(10, 31) for coffee in unique_coffees}
print(coffee_prices)

{'Latte': 16, 'Hot Chocolate': 29, 'Americano': 24, 'Americano with Milk': 20, 'Cocoa': 17, 'Cortado': 30, 'Espresso': 16, 'Cappuccino': 28}

In [162]:
#Lets add new column Price/unit and generate a  random price between 10-30 for each unique coffee_name
unique_coffees = df_sales['coffee_name'].unique()
coffee_prices = {}
np.random.seed(42)
for i in unique_coffees:
  coffee_prices[i] = np.random.randint(10, 31)
df_sales['Price/unit'] = df_sales['coffee_name'].map(coffee_prices)
df_sales

,date,datetime,cash_type,card,coffee_name,Quantity,Price/unit
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,Latte,3,16
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,Hot Chocolate,3,29
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,Hot Chocolate,3,29
3,01-03-2024,46:33.0,card,ANON-0000-0000-0003,Americano,1,24
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,Latte,3,16
...,...,...,...,...,...,...,...
3631,23-03-2025,34:54.9,card,ANON-0000-0000-1158,Cappuccino,2,28
3632,23-03-2025,43:37.4,card,ANON-0000-0000-1315,Cocoa,3,17
3633,23-03-2025,44:16.9,card,ANON-0000-0000-1315,Cocoa,2,17
3634,23-03-2025,47:28.7,card,ANON-0000-0000-1316,Americano,3,24
3635,23-03-2025,11:38.6,card,ANON-0000-0000-1275,Latte,2,16

In [164]:
#Lets add new column total amount which gives the product of price and qty
df_sales['total_amount'] = df_sales['Price/unit'] * df_sales['Quantity']
df_sales.head()

,date,datetime,cash_type,card,coffee_name,Quantity,Price/unit,total_amount
0,01-03-2024,15:50.5,card,ANON-0000-0000-0001,Latte,3,16,48
1,01-03-2024,19:22.5,card,ANON-0000-0000-0002,Hot Chocolate,3,29,87
2,01-03-2024,20:18.1,card,ANON-0000-0000-0002,Hot Chocolate,3,29,87
3,01-03-2024,46:33.0,card,ANON-0000-0000-0003,Americano,1,24,24
4,01-03-2024,48:14.6,card,ANON-0000-0000-0004,Latte,3,16,48

In [165]:
#Compute total revenue, average price, total items per category using agg
df_sales.groupby('coffee_name').agg({'total_amount':'sum','Price/unit':'mean','Quantity':'sum'})

                     total_amount  Price/unit  Quantity
coffee_name
Americano                   27360        24.0      1140
Americano with Milk         33160        20.0      1658
Cappuccino                  27132        28.0       969
Cocoa                        8092        17.0       476
Cortado                     17550        30.0       585
Espresso                     4320        16.0       270
Hot Chocolate               16646        29.0       574
Latte                       25328        16.0      1583

#**Q6. Pivot & melt**

- Create a pivot table (e.g., index=month, columns=region, values=revenue, aggfunc=sum).

- Unpivot it back with melt and verify it matches long format (ignoring sort/in

Q7. Join/Merge

- Merge two DataFrames (e.g., orders + customers) with an inner join.

- Count how many orders were lost in a left join vs inner join (unmatched keys).

Q8. Datetime & resample

- Convert a date column to datetime, set it as index.

- Resample monthly and compute monthly sums.

- Compute a 3-month moving average.

Q9. Apply & transform

- Standardize a numeric column within each group (z-score per group) using groupby().transform.

Q10. Categoricals & performance

- Convert a high-cardinality text column to category.

- Measure memory before/after (in MB).

- Compare speed of a groupby on text vs categorical column (use %timeit in notebook).